name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-west-2

    - name: SSH into EC2 instance and deploy
      run: |
       ssh -o StrictHostKeyChecking=no ubuntu@54.212.20.31 'git clone https://github.com/udaychopade27/NestJS-App-Deployment-.git && cd NestJS-App-Deployment- && npm install && npm run build && pm2 restart all'

